server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: CRRa0701
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

jwt:
  secret: MiClaveSecretaMuyLarga1234567890
  expirationMs: 86400000
